PROFILE: "stage"
PORT: 8000
SERVER_NAME: "url-generator-1"
DB_USER: ""
DB_PASSWORD: ""
DB_HOST: ""
DB_PORT: 3306
DB_NAME: ""
ALLOWED_ORIGINS: ""
REDIS_ADDRESS: ""
REDIS_PASSWORD: ""
TOKEN_RANGE_SIZE: 999
REACT_APP_URL: ""